import { type Module, inject } from 'langium';
import type { 
    DefaultSharedModuleContext, 
    LangiumServices, 
    LangiumSharedServices,
    PartialLangiumServices,
    PartialLangiumSharedServices 
} from 'langium/lsp';
import { createDefaultModule, createDefaultSharedModule } from 'langium/lsp';
import { DomainLangGeneratedModule, DomainLangGeneratedSharedModule } from './generated/module.js';
import { registerValidationChecks } from './validation/domain-lang-validator.js';
import { QualifiedNameProvider } from './lsp/domain-lang-naming.js';
import { DomainLangScopeComputation } from './lsp/domain-lang-scope.js';
import { DomainLangFormatter } from './lsp/domain-lang-formatter.js';
import { DomainLangHoverProvider } from './lsp/hover/domain-lang-hover.js';
import { DomainLangCompletionProvider } from './lsp/domain-lang-completion.js';
import { DomainLangCodeActionProvider } from './lsp/domain-lang-code-actions.js';
import { ImportResolver } from './services/import-resolver.js';
import { WorkspaceManager } from './services/workspace-manager.js';
import { DomainLangWorkspaceManager } from './lsp/domain-lang-workspace-manager.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type DomainLangAddedServices = {
    imports: {
        ImportResolver: ImportResolver,
        WorkspaceManager: WorkspaceManager
    },
    references: {
        QualifiedNameProvider: QualifiedNameProvider
    },
    lsp: {
        Formatter: DomainLangFormatter,
        HoverProvider: DomainLangHoverProvider,
        CompletionProvider: DomainLangCompletionProvider,
        CodeActionProvider: DomainLangCodeActionProvider
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type DomainLangServices = LangiumServices & DomainLangAddedServices

const DomainLangSharedModule: Module<LangiumSharedServices, PartialLangiumSharedServices> = {
    workspace: {
        WorkspaceManager: (services: LangiumSharedServices) => new DomainLangWorkspaceManager(services)
    }
};

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const DomainLangModule: Module<DomainLangServices, PartialLangiumServices & DomainLangAddedServices> = {
    imports: {
        ImportResolver: (services) => new ImportResolver(services),
        WorkspaceManager: () => new WorkspaceManager({ autoResolve: false, allowNetwork: false })
    },
    references: {
        ScopeComputation: (services) => new DomainLangScopeComputation(services),
        QualifiedNameProvider: () => new QualifiedNameProvider()
    },
    lsp: {
        Formatter: () => new DomainLangFormatter(),
        HoverProvider: (services) => new DomainLangHoverProvider(services),
        CompletionProvider: (services) => new DomainLangCompletionProvider(services),
        CodeActionProvider: () => new DomainLangCodeActionProvider()
    },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createDomainLangServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    DomainLang: DomainLangServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        DomainLangGeneratedSharedModule,
        DomainLangSharedModule
    );
    const DomainLang = inject(
        createDefaultModule({ shared }),
        DomainLangGeneratedModule,
        DomainLangModule
    );
    shared.ServiceRegistry.register(DomainLang);
    registerValidationChecks(DomainLang);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, DomainLang };
}