/*
 * generated by Xtext 2.25.0
 */
package org.domainlang.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DomainLangStandaloneSetup extends DomainLangStandaloneSetupGenerated {

	public static void doSetup() {
		new DomainLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
