/*
 * generated by Xtext 2.25.0
 */
package org.domainlang.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainLangRuntimeModule extends AbstractDomainLangRuntimeModule {
}
