import type { Module } from 'langium';
import { inject } from 'langium';
import { DomainLangGeneratedModule, DomainLangGeneratedSharedModule } from './generated/module.js';
import { DomainLangValidator, registerValidationChecks } from './lsp/domain-lang-validator.js';
import { QualifiedNameProvider } from './lsp/domain-lang-naming.js';
import { DomainLangScopeComputation } from './lsp/domain-lang-scope.js';
import { DomainLangFormatter } from './lsp/domain-lang-formatter.js';
import { DomainLangHoverProvider } from './lsp/domain-lang-hover.js';
import { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, PartialLangiumServices, createDefaultModule, createDefaultSharedModule } from 'langium/lsp';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type DomainLangAddedServices = {
references: {
        QualifiedNameProvider: QualifiedNameProvider
    },
    validation: {
        DomainLangValidator: DomainLangValidator
},
    lsp: {
        Formatter: DomainLangFormatter,
        HoverProvider: DomainLangHoverProvider
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type DomainLangServices = LangiumServices & DomainLangAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const DomainLangModule: Module<DomainLangServices, PartialLangiumServices & DomainLangAddedServices> = {
    validation: {
        DomainLangValidator: () => new DomainLangValidator()
},
    references: {
        ScopeComputation: (services) => new DomainLangScopeComputation(services),
        QualifiedNameProvider: () => new QualifiedNameProvider()
    },
    lsp: {
        Formatter: () => new DomainLangFormatter(),
        HoverProvider: (services) => new DomainLangHoverProvider(services),
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createDomainLangServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    DomainLang: DomainLangServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        DomainLangGeneratedSharedModule
    );
    const DomainLang = inject(
        createDefaultModule({ shared }),
        DomainLangGeneratedModule,
        DomainLangModule
    );
    shared.ServiceRegistry.register(DomainLang);
    registerValidationChecks(DomainLang);
    return { shared, DomainLang };
}
