/*
 * generated by Xtext 2.25.0
 */
package org.domainlang.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DomainLangUiModule extends AbstractDomainLangUiModule {

	public DomainLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
