/*
 * generated by Xtext 2.25.0
 */
package org.domainlang.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.domainlang.dsl.DomainLangRuntimeModule;
import org.domainlang.dsl.DomainLangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DomainLangIdeSetup extends DomainLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomainLangRuntimeModule(), new DomainLangIdeModule()));
	}
	
}
